ARG STRAPI_VERSION

FROM strapi/strapi:${STRAPI_VERSION}

ARG TIMEZONE

# set time zone
RUN apk add tzdata \
  && cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
  && apk del tzdata

EXPOSE 1337

ADD start.sh /
RUN chmod +x /start.sh
CMD ["/start.sh"]
